name: llada
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy>=1.23.4,<2.0.0
  - pip:
    - torch>=1.13.1
    - transformers==4.38.2
    - gradio
    - accelerate>=0.19.0
    - huggingface_hub==0.34.1
    - tokenizers>=0.13.3

